it_lowlevel = [
    ("Was ist ein Byte?", "Teil der \nHardware", "Maßeinheit \nfür Datenmenge", "Programmier-\nsprache", "Bearbeitungs-\nprogramm", "Maßeinheit \nfür Datenmenge", "kein Hinweis"),
    ("Für was steht die Abkürzung IT?",  "Informatik \nund Technik", "Integrationstaktik", "Intelligenztest","Informations-\ntechnologie", "Informations-\ntechnologie", "kein Hinweis"),
    ("Wofür steht die Abkürzung IoT?", "Information \nof Technology", "Internet \nof Things", "Innovation \non Transformation", "Information \non Television", "Internet \nof Things", "kein Hinweis"),
    ("Was ist SQL?",  "Betriebssystem", "Form der \nSpeicherung","Datenbank-\nsprache", "Dateiformat \nfür Fotos","Datenbank-\nsprache", "kein Hinweis"),
    ("Wie viele Bits hat ein Byte?", "2", "4", "6", "8", "8", "kein Hinweis"),
    ("Welche der folgenden Technologien bildet \ndie Grundlage des World Wide Web?", "HTTP", "GPS", "USB", "WLAN", "HTTP","Kein Hinweis" ),
    ("Wie nennt man kostenlose Computerprogramme?", "Malware", "Zeroware", "Freeware", "Software", "Freeware", "kein Hinweis"),
    ("Was ist JavaScript?", "Anti-Virus-\nProgramm",  "Schriftart","Programmier-\nsprache", "MS-Office \nProdukt", "Programmier-\nsprache", "kein Hinweis"),
    ("Was bedeutet die Abkürzung 'HTML'?", "Hyperlink & Text \nMarkup Language", "Hypertext \nMarkup Language", "Home Tool \nMarkup Language", "Hyper Text \nManipulate Language", "Hypertext \nMarkup Language","Kein Hinweis"),
    ("Welche der folgenden ist keine Suchmaschine?", "Google", "Bing", "Yahoo", "Java","Java", "kein Hinweis"),    
    ("Wie lautet der Name des Windows-Grafik Editors?", "Gimp", "Paint", "Photoshop", "Word","Paint","Kein Hinweis"),
    ("Welche der folgenden Komponenten ist \nTeil der Hardware eines Desktop-Computers?", "Microsoft Word", "Monitor", "Windows 10", "Microsoft Excel" , "Monitor","Kein Hinweis"),
    ("Welche Art von Dokumenten wird \nim WWW am häufigsten verwendet?", "PDF-Dateien", "PowerPoint-\nPräsentationen", "HTML-\nDokumente", "Excel-Tabellen" , "HTML-\nDokumente","Kein Hinweis"),
    ("Welches der folgenden ist ein Betriebssystem?", "MAC OSX", "DOS", "Windows 7", "Alle","Alle","Kein Hinweis"),
    ("Was versteht man unter USB?", "Universal \nSatellite Bus", "Universal \nSystem Bus", "Universal \nSerial Bus", "Universal \nSoftware Bus","Universal \nSerial Bus", "kein Hinweis"),
    ("Welche der folgenden ist kein Peripheriegerät?", "Diskettenlaufwerk", "Festplatte", "Grafiktablett", "Arbeitsspeicher","Arbeitsspeicher","Kein Hinweis"),
]

it_midlevel = [
    ("Wer ist Teilnehmer des Marathons; Game Jam?", "Keine \nEinschränkung", "Computerspiel-\nDesigner", "Konsolen-\nDesigner", "Spiele-Tester","Computerspiel-\nDesigner", "kein Hinweis"),
    ("Welche Begriffe bezeichnen eine Form \ndes Speicherns?", "Cookie, Cache, ROM", "RAM, Cookie, Cache", "RAM und ROM", "Cookie und Cache", "Cookie, Cache, ROM", "kein Hinweis"),
    ("Was ist die Hauptfunktion von CSS?", "Datenbankabfrage", "Layout & Gestaltung\nvon Webseiten", "Serverkonfiguration", "JavaScript-\nProgrammierung", "Layout & Gestaltung\nvon Webseiten","Kein Hinweis"),
    ("Steve Jobs war ein Gründer \noder Mitbegründer von…", "Apple und Dell", "HP und Apple", "Next und Apple", "Apple und Microsoft",  "Next und Apple","Kein Hinweis"),
    ("Wie heißen Netzwerkgeräte, die den \noptimalen Pfad ermitteln, über den der \nNetzwerkverkehr weitergeleitet werden soll?", "Router", "Schalter", "Hub", "Server","Router","Kein Hinweis"),
    ("Welches Tier ist das Maskottchen des \nLinux-Systems?", "Pinguin", "Fuchs", "Bär", "Biber","Pinguin","Kein Hinweis"),
    ("Wer gilt als Erfinder des World Wide Web (WWW)?", "Steve Jobs", "Tim Berners-Lee", "Bill Gates", "Mark Zuckerberg","Tim Berners-Lee","Kein Hinweis"),
    ("Von welcher Firma nahm Steve Jobs \ndie Idee für die grafische Benutzeroberfläche \nmit einer Maus?", "Microsoft", "Amiga", "IBM","Xerox", "Xerox","Kein Hinweis"),
    ("Welcher Firmenname ist keine Abkürzung?", "CERN", "ACER", "INTEL", "VARTA","ACER","Kein Hinweis"),
    ("Woher kommt das Zeichen ‚@‘?", "Aus dem \nArabischen", "Aus dem \nGriechischen", "Aus dem \nLateinischen", "Symbol, nur für \nMail erstellt","Aus dem \nLateinischen","Kein Hinweis"),
    ("Welcher Übertragungsmodus wird \nbei Glasfaserkabeln zur Übertragung von Daten \nüber große Entfernung verwendet?", "Infrarotstrahlung", "Multimode Fasern", "Radiowellen", "Singlemode Fasern","Singlemode Fasern","Kein Hinweis"),
    ("Wann wurde der erste Computer erstellt?", "1945", "1943", "1939", "1941","1939","Kein Hinweis"),
    ("Welche der folgenden ist kein Peripheriegerät?", "Diskettenlaufwerk", "Festplatte", "Grafiktablett", "Arbeitsspeicher","Arbeitsspeicher","Kein Hinweis"),
    ("Eine einzige Transaktion mit der Digitalwährung \nBitcoin verbraucht im Vergleich mit der Buchung \neiner Kreditkarte wieviel Male mehr Energie?", "200-mal mehr", "10.000-mal mehr", "50.000-mal mehr", "1.000-mal mehr","10.000-mal mehr","Kein Hinweis"),
    ("In welchem Monat /Jahr wurde \ndas iPhone gelauncht und startete damit \ndie Smartphone Revolution?", "Januar 2007", "September 2005", "September 2008", "März 2009","Januar 2007","Kein Hinweis"),
    ]
it_highlevel = [
    ("Welcher Informatiker entwickelte \nein Textsatzsystem mit eingebauter Makrosprache \nunter dem Namen TeX?", "Vaughan Pratt", "Donald Knuth", "James Morris", "Manuel Blum", "Donald Knuth","Dieser Informatiker ist auch \nfür das The Art of Computer Programming-Buch bekannt"),
    ("Wie lautet der Binärcode für die Dezimalzahl 20?", "11101", "10011", "10110", "11100", "10011", "Der Binärcode für die Dezimalzahl 20 beginnt mit 10"),
    ("Wann gab es den ersten tragbaren Computer?", "1981", "1987", "1991", "1983", "1981","Dieses Ereignis fand in den frühen 1980er Jahren statt"),
    ("Wofür steht das QR in QR-Code?",  "Quote React", "Quest Response","Quick Response", "Question Reaction", "Quest Response","Das QR im QR-Code steht für zwei englische Wörter, die die Schnelligkeit und Effizienz dieses Codes betonen."),
    ("Welche Programmiersprache wurde von \nGuido van Rossum entwickelt und ist für \nihre Einfachheit und Lesbarkeit bekannt?", "Java", "C++", "Python", "Ruby", "Python","Die Sprache ist nach einer britischen Komikergruppe benannt." ),
    ("Welche Programmiersprache wird häufig \nfür die Entwicklung von Webanwendungen \nund dynamischen Websites verwendet?", "HTML", "CSS", "JavaScript", "PHP", "JavaScript","Sie beinhaltet den Namen einer objektorientierten Programmiersprache." ),
    ("Welche der folgenden Datentypen wird \nin Java verwendet, um dezimale Zahlen \nmit Fließkommazahlen in Java darzustellen?", "int", "double", "char", "Boolean", "double","Die Bezeichnung bezieht sich auf die Anzahl der Dezimalstellen, die der Datentyp speichern kann, und die Genauigkeit, mit der er Gleitkommazahlen repräsentiert" ),
    ("Wie wird in Python eine Zeichenkette (String) \nin Kleinbuchstaben umgewandelt?", "str.lower()", "str.upper()", "str.capitalize()", "str.casefold()" , "str.casefold()","Der Name leitet sich von Kleinbuchstaben falten oder Buchstaben in Kleinbuchstaben umwandeln ab"),
    ("Was bedeutet ELT in Bezug auf Datenintegration?", "Extract, Load, Test", "Extract, Load,\n Transform", "Extract, Link,\n Transform", "Extract, Log,\n Transfer" , "Extract, Load,\n Transform","Die Buchstaben stehen für die verschiedenen Phasen des Prozesses.\nDarunter versteht man den Prozess, den datengesteuerte Unternehmen verwenden, um Daten aus verschiedenen Quellen zu erfassen und dann zusammenzuführen, um Erkennungen, Berichterstellung, Analysen und die Entscheidungsfindung zu unterstützen."),
    ("Welcher Schritt des ELT-Prozesses beinhaltet \ndie Bereinigung, Aggregierung und Umwandlung \nvon Daten, um sie für Analysen vorzubereiten?", "Extract", "Load", "Transform", "Extract und Load" , "Transform","Es ist die letzte Phase im Prozess."),
    ("Welche der folgenden Aufgaben kann \nmit Power BI durchgeführt werden?", "E-Mail-\nKommunikation", "Textverarbeitung", "Datenvisualisierung \nund -analyse", "3D-Modellierung" , "Datenvisualisierung \nund -analyse","Das Unternehmen kann auf dessen Basis Entscheidungen treffen."),
    ("Welche der folgenden Datenquellen kann direkt \nin Power BI importiert und analysiert werden?","Vielzahl \nvon Datenquellen", "Nur Excel-Dateien", "Nur \nSQL-Datenbanken",  "Nur CSV-Dateien", "Vielzahl \nvon Datenquellen","Kein Hinweis" ),
    ("Was ist ein Schlüssel in einer \nrelationalen Datenbank?", "Verschlüsselungs-\nwert", "Datenbankabfrage", "Attribut \nzur Eindeutigkeit", "Speicherungsart" , "Attribut \nzur Eindeutigkeit","Ein Schlüssel ist ein Attribut oder eine Kombination von Attributen in einer Tabelle, \ndie sicherstellt, dass jede Person, Objekt, etc. identifiziert werden kann.")  ,
    ("Was versteht man unter Datenschutz?", "Informations-\nveröffentlichung", "Sicherung \nder Privatsphäre", "personenbezogener \nInformationsschutz", "Kontrolle über \npersönliche Daten" , "personenbezogener \nInformationsschutz","Alle Gesetze, die auf den Schutz dieser Daten abzielen und \nden Datenmissbrauch durch Dritte verhindern sollen."),
    ("Wofür wird SAP in Unternehmen häufig verwendet?","Verwaltung von \nGeschäftsprozessen", "Herstellung \nvon Geräten", "Analyse \nvon Klimadaten",  "Entwicklung \nvon Videospielen" , "Verwaltung von \nGeschäftsprozessen","SAP optimiert die Unternehmensperformance einfach, schnell und sicher."),
    ("Welche der folgenden Hardwarekomponenten \nist verantwortlich für die kurzfristige Speicherung \nvon Daten, die vom Prozessor verwendet werden?", "RAM", "Festplatte", "CPU", "Monitor", "RAM","Dieser Speichertyp ist flüchtig." ),
    ("Welcher DNS-Datensatztyp wird  \nvon Mail-Servern verwendet, um zu bestimmen, \nwohin E-Mail gesendet werden sollen?", "CNAME \nResource Record", "A \nResource Record", "SMTP \nResource Record", "MX \nResource Record","MX \nResource Record",  "Das Kürzel bedeutet übersetzt E-Mail-Austausch."),
]

