science_lowlevel = [
    ("Wie viele Planeten gibt es?", "9", "11", "12", "8", "8","Kein Hinweis"),
    ("Wie viele Knochen gibt es \nim menschlichen erwachsenen Körper?", "206", "270", "244", "350", "206","Kein Hinweis"),
    ("Was ist der härteste natürliche Stoff auf der Erde?", "Gold", "Eisen", "Diamant", "Granit", "Diamant","Kein Hinweis"),
    ("Welches ist der größte Planet \nin unserem Sonnensystem?", "Merkur", "Venus", "Jupiter", "Saturn", "Jupiter","Kein Hinweis"),
    ("Wie viele Gehirne und \nwie viele Herzen hat ein Oktopus?", "9 Gehirne, \n3 Herzen", "3 Gehirne, \n8 Herzen", "5 Gehirne, \n3 Herzen", "3 Gehirne, \n9 Herzen", "9 Gehirne, \n3 Herzen", "Kein Hinweis"),
    ("Welches ist das schnellste Landtier der Welt?", "Gepard", "Strauß", "Tiger", "Panda", "Gepard", "Kein Hinweis"),
    ("Welches ist die einzige gerade Primzahl?",  "4", "6", "8","2", "2", "Kein Hinweis"),
    ("Wie viele Zustände der Materie gibt es?", "4", "3", "5", "6", "4", "Kein Hinweis"),
    ("Was ist kein Aggregatzustand?", "Flüssig", "Fest", "Gas", "Gel", "Gel", "Kein Hinweis"),
    ("Was ist das häufigste \nchemische Element im Universum?", "Chlor", "Platin", "Brom", "Wasserstoff", "Wasserstoff", "Kein Hinweis"),
    ("Wasser besteht aus den Elementen \nWasserstoff und…", "Stickstoff", "Kohlenstoff", "Natrium", "Sauerstoff", "Sauerstoff", "Kein Hinweis"),
    ("Welche Eigenschaften trifft nicht auf Sauerstoff zu?", "Brennbar", "Gasförmig", "Instabil", "farblos", "Instabil", "Kein Hinweis"),
    ("Was genau untersucht die Physik", "Den menschlichen\nKörper", "Phänomene\nder Natur", "Bereiche \nder Technik", "Größen und \nEinheiten", "Phänomene\nder Natur", "Kein Hinweis"),
    ("Mit welcher Substanz wird das Wasser \nin Schwimmbädern oft versetzt?", "Chlor", "Brom", "Salz-Elektrolyse", "UV-Desinfektion", "Chlor", "Kein Hinweis"),
    ("Was ist am schnellsten?", "Schall", "Licht", "Rakete", "Wind", "Licht", "Kein Hinweis"),
    
]
science_midlevel = [
    ("Was ist das spezielle am Chromosomensatz \nbei Menschen mit Down-Syndrom?", "Chromosom X & Y\nist vertauscht", "Chromosom 20 fehlt", "Chromosomen \nfehlen", "dreifache \nChromosom 21", "dreifache \nChromosom 21", "Kein Hinweis"),
    ("Wofür steht die DNA?", "Desoxyribonuklein-\nsäuresequenz", "Desoxyribonukleotid-\nansammlung", "Deoxyribonucleotid\n-Assoziation", "Desoxyribonuklein-\nsäure", "Desoxyribonukleinsäure", "Kein Hinweis"),
    ("Welches ist das Hauptgas, \naus dem die Erdatmosphäre besteht?", "Stickstoff", "Kohlendioxid", "Sauerstoff", "Wasserstoff", "Stickstoff", "Kein Hinweis"),
    ("Welches Element besitzt die kleinste Ordnungszahl?", "Magnesium", "Titan", "Quecksilber", "Xenon", "Magnesium", "Kein Hinweis"),
    ("Welches gehört zu den \ngrundlegenden Zuständen der Materie?", "Suprafluidität", "Plasma", "Supraleiter", "Ferromagnetismus", "Plasma", "Kein Hinweis"),
    ("In welchen Materialien breitet sich \nSchall am schnellsten aus?",  "Luft", "Gewebe", "Wasser","Vakuum", "Wasser", "Kein Hinweis"),
    ("Wie viel DNS haben Menschen \nund Schimpansen ungefähr gemeinsam?",  "79 %", "61 %", "98 %","91 %", "98 %", "Kein Hinweis"),
    ("Wie lange dauert es ungefähr, \nbis das Licht der Sonne die Erde erreicht?", "8 Minuten", "8 Sekunden", "8 Stunden", "8 Tage", "8 Minuten", "Kein Hinweis"),
    ("Womit beschäftigte sich Stephen Hawking?", "DANN-Struktur", "schwarzen Löchern", "Schallwellen", "Wechselwirkung \ndes Lichts", "schwarzen Löchern", "Kein Hinweis"),
    ("Welche der Personen ist kein berühmter Physiker?", "Sir Isaac Newton", "Charles Darwin", "Galileo Galilei", "Marie Curie", "Charles Darwin", "Kein Hinweis"),
    ("Welcher der Buchstaben \nkommt nicht im Periodensystem vor?",  "Y", "X", "I", "J","J", "Kein Hinweis"),
    ("Wie viele Knochen haben Neugeborene?", "206", "240", "350", "100", "350", "Kein Hinweis"),
    ("Welches ist das schwerste \nOrgan des menschlichen Körpers?",  "Lunge", "Leber", "Herz", "Gehirn", "Leber", "Kein Hinweis"),
    ("Welches Metall ist der beste Leiter für Elektrizität?", "Gold", "Eisen", "Silber", "Aluminium", "Silber", "Kein Hinweis"),
    ("Was fand Albert Einstein heraus?", "Kraft-Leistung-\nVerbindung", "Raum-Zeit-\nAbhängigkeit", "Beständigkeit \nvon Eis", "Tiefe \ndes Meeres", "Raum-Zeit-\nAbhängigkeit", "Kein Hinweis"),
]
science_highlevel = [
    ("Was ist die Avogadro-Konstante?", "6,02214076 \n× 10^23", "42", "3,14159265", "9,80665", "6,02214076 \n× 10^23"," Diese Zahl ist so groß, \ndass sie in der Praxis oft in wissenschaftlichen Berechnungen und Experimenten verwendet wird, \num winzige Mengen von Substanzen zu beschreiben."),
    ("Was ist das dritthäufigste \nchemische Element im Erdmantel?", "Sauerstoff", "Eisen", "Silizium", "Aluminium", "Silizium","Steht mit der Ordnungszahl 14 an der 14. Stelle \nund in der dritten Periode des Periodensystems"),

    ("Welches Elementsymbol besitzt Uran?", "Ua", "Un", "Ur", "U",
      "U",  "Das Element Uran hat ein einfaches Symbol."),
      
    ("In welchem Jahr wurde Pluto \nals Zwergplanet neu eingestuft?", "2004", "2005", "2006", "2007", "2006", "Im selben Jahr fand die Fußball-Weltmeisterschaft in Deutschland statt."),
    ("Mit welchem Begriff haben \nAstrophysiker häufig zu tun?", "Grünverschiebung", "Rotverschiebung", "Weißverschiebung", "Gelbverschiebung", "Rotverschiebung", "Dieser Begriff bezieht sich auf das Licht \nvon weit entfernten Objekten im Universum."),
    ("100 Grad Celsius entsprechen?", "25 Delisle", "173 Kelvin", "212 Fahrenheit", "571 Rankine", "212 Fahrenheit", "Dies ist der Siedepunkt von Wasser bei atmosphärischem Druck"),
    ("Wie viele Tage dauert es auf der Erde, \nbis sich die Venus einmal um ihre Achse dreht?", "243", "251", "170", "183", "243", "Die Venus hat eine ungewöhnlich langsame Rotation."),
    ("Welches Element ist nicht radioaktiv?", "Bismut", "Astat", "Radon", "Strontium", "Strontium", " Dieses Element wird in einigen Anwendungen der Kernphysik genutzt, ohne selbst radioaktiv zu sein."),
    ("Wie schnell muss mindestens eine Rakete sein, \num in den Weltraum zu gelangen?", "7,91 km/s", "11,91 km/s", "16,7 km/s", "Abhängig \nvom Gewicht", "7,91 km/s", "Sie ist die sogenannte erste kosmische Geschwindigkeit – das ist mehr als das 20-fache der Schallgeschwindigkeit."),
    ("Welches hat die höchste Temperatur?", "Oberfläche \nder Sonne", "Blitze", "Innerer Erdkern", "Lavaströme", "Blitze", "Diese Erscheinungen entstehen durch extreme elektrische Entladungen."),
    ("Welchen Schmelzpunkt besitzt Blei?", "619,4°C", "317,43°C", "83,91°C", "1426,54°C", "317,43°C", "Blei ist ein Metall mit einem vergleichsweise niedrigen Schmelzpunkt"),
    ("Bei welcher Temperatur sind \nCelsius und Fahrenheit gleich?",  "40", "0","-40", "-100", "-40", "1 °C = 33,8 °F"),
    ("Welches sind keine Bestandteile \neiner tierischen Zelle?", "Mitochondrien", "Chloroplasten", "Lysosomen", "Endoplasmatisches \nReticulum", "Chloroplasten", "Diese Organellen sind spezifisch in pflanzlichen Zellen zu finden"),
    ("Welches Zellkompartiment ist \nfür die Fotosynthese verantwortlich?", "Nukleus", "Vakuole", "Zellwand", "Chloroplast", "Chloroplast", "In ihnen befindet sich das Chlorophyll, \nan dem die Reaktionen der Photosysteme I und II ablaufen. "),
    ("Was ist keine Phase der „Mitose“?", "Prophase", "Postphase", "Telophase", "Anaphase", "Postphase", "In der Mitose, einem wichtigen Prozess der Zellteilung, gibt es vier Hauptphasen. \nEine die hier nicht genannte Phase ist die Metaphase."),
   
]